[package]
name = "msp432p401r-hal"
version = "0.1.0"
authors = ["Caio Tavares <caio.tavares11@gmail.com>", "José Cláudio S. Jr. <joseclaudio.silvajr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
cortex-m = "0.6.0"
cortex-m-rt = "0.6.10"
msp432p401r-pac = "0.1.0"
embedded-hal = "1.0.0-alpha.3"
