name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          default: true
          target: "thumbv7em-none-eabihf"
          toolchain: nightly

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      
